In [24]:
import numpy as np

#Creating arrays

arr1 = np.array([6, 7.5, 8, 0, 1])
# print(arr1)
# print(arr1.dtype)

#From nested lists (2D)
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]]
)
# print(arr2)

# print(arr2.ndim, arr2.shape)

#Zeros, ones, empty
zeros = np.zeros(5)
print(zeros)

ones = np.ones((2, 3)) # you can specify the matrix that you want
print(ones)

arr_empty = np.empty((2, 2)) # creating an uninitialized array
print(arr_empty)

#Ranges
arr_range = np.arange(6)
print(arr_range)


[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6.  7.5]
 [8.  1. ]]
[0 1 2 3 4 5]


In [27]:
#Exercise
a = np.zeros(9).reshape(3,3) # array of 9 zeros

#set a center to 5
a[1, 1] = 5

print(a)


[[0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]


In [36]:
# Data types and casting
arr = np.array([1, 2, 3], dtype = np.float64)
# print(arr)

arr_i = arr.astype(np.int32) # cast (copy) to int32
# print(arr_i, arr_i.dtype)

s = np.array(["1.25", "-9.6", "42"])
print(s.astype(float))

[1. 2. 3.]
[1 2 3] int32
[ 1.25 -9.6  42.  ]


In [41]:
# Exercise: Casting

arr_cast = np.array([3.7, -1.2, 0.0])
print(arr_cast)
arr_cast_int = arr_cast.astype(int)
print(arr_cast_int)

#Alternative
print(arr_cast.astype(int))


[ 3.7 -1.2  0. ]
[ 3 -1  0]
[ 3 -1  0]


In [49]:
# Vectorized arithmetric and comparisons

arr = np.array([
        [1., 2., 3.],
        [4., 5., 6.]])
# print(arr)
print(1 / arr)

arr2 = np.array([
    [0, 4., 1.],
    [7., 2., 12.]
])

print(arr2 > arr)


[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[False  True False]
 [ True False  True]]


In [72]:
# Exercise BMI

w = np.array([60, 70, 80])
h = np.array([1.7, 1.75, 1.8])

bmi = w / (h ** 2)
print(np.round(bmi, 2))

[20.76 22.86 24.69]


In [95]:
# Indexing and slicing 
arr = np.arange(10)
# print(arr)
# print(arr[5])
s1 = arr[5:8]
# print(s1)
# print(s1.ndim, s1.shape)

s1[:] = 99 # modifies the origintal (slices are VIEWS)
# print(s1)

# 2D indexing
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# print(arr2d)
# print(arr2d[(0, 2)])
# print(arr2d[:2, 1:])

# Exercise

arr2d[:2, 1:] = 0
print(arr2d)


[[1 0 0]
 [4 0 0]
 [7 8 9]]


In [99]:
# Boolen Indexing (filters)

names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
# print(names)

data = np.array([
    [4,7],
    [0,2],
    [-5,6],
    [0,0],
    [1,2],
    [-12,-4],
    [3,4]
    
])
mask = (names == "Bob") # [ True False False  True False False False]
print(mask)

print(data[(names == "Bob") | (names == "Will")])


[ True False False  True False False False]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]


In [102]:
# Exercise
# Task: Set all negative entries in data to 0

data[data < 0] = 0
print(data)

[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]


In [110]:
# Fancy Indexing (integer array)

arr = np.arange(32).reshape(8,4)
print(arr)

print(arr[[1,5, 7, 2], [0, 3, 1, 2]]) # elements (1,0), (5,3), (7, 1), (2,2)

# Rectangualr subset in new order:
arr[[1, 5, 7, 2]] [:, [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(5, 3)
