In [6]:
## install & import numpy
import numpy as np
np.__version__

'2.1.3'

In [24]:
## Create Arrays
a = np.array([1, 2, 3, 4, 5]) # 1D array
a

b = np.array([[1, 2, 3],[4, 5, 6]])
b

z = np.zeros((2,3))
z

o = np.ones((2,3))
o

f = np.full((2,3), 7)
f

r = np.arange(0, 10, 2)
r

l = np.linspace(0, 1, 5)
l

i = np.eye(2)
i

array([[1., 0.],
       [0., 1.]])

In [29]:
# Dtype (data types)
x = np.array([1, 2, 3], dtype = np.float32)
print(x.dtype)

y = x.astype(np.int64)
print(y.dtype)


float32
int64


In [36]:
# Inspecting arrays

m = np.arange(12).reshape(3,4)
print(m)

print(m.ndim) # 2D arrayb
print(m.shape)
print(m.size)
print(m.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)
12
int64


In [41]:
# Indexing and Slicing
A = np.array([[10, 11, 12],
             [20, 21, 22],
             [30, 31, 32]])
print(A[0, 1]) # 11
print(A[1])
print(A[:, 0]) 
print(A[0:2, 1:3])

11
[20 21 22]
[10 20 30]
[[11 12]
 [21 22]]


In [56]:
# Boolean Masking (filter by condition)
v = np.array([3, 6, 1, 9, 2, 8])
mask = v > 4
print(mask)
print(v[mask])

# combine conditions with & (and), | (or),  ~ (not)
print(v[(v > 2) & (v % 2 == 0)] )b


[False  True False  True False  True]
[6 9 8]
[6 8]


In [58]:
# Fancy Indexing (by Integer arrays)
w = np.array([10, 20, 30, 40, 50])
idx = np.array([4, 0, 3])
print(w[idx])

[50 10 40]


In [62]:
# Vectorized Operations (element-wise)
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(a * b)
print(b / a)
print(a ** 2)


[11 22 33]
[10 40 90]
[10. 10. 10.]
[1 4 9]


In [72]:
# Broadcasting
M = np.arange(6).reshape(2,3)
print(M)
V = np.array([10, 100, 1000])


print(M + V)

col = np.array([[1], [2]])
print(col)

print( M + col)


[[0 1 2]
 [3 4 5]]
[[  10  101 1002]
 [  13  104 1005]]
[[1]
 [2]]
[[1 2 3]
 [5 6 7]]


In [94]:
# Universal Functions (ufuncs)

x = np.array([1, 4, 9, 16], dtype = float)
print(np.sqrt(x))
print(np.log(x))
print(np.maximum(x, 5))

#Try
x = [-1, 0, 1]
print(np.exp(x))
print(np.exp(x) / (1 + np.exp(x)))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[ 5.  5.  9. 16.]
[0.36787944 1.         2.71828183]
[0.26894142 0.5        0.73105858]
